[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "runner"
path = "src/runner.rs"

[[bin]]
name = "run_day"
path = "src/run_day.rs"

[dependencies]
dedent = "0.1.1"
regex = "1.11.1"
