[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "runner"
path = "src/runner.rs"

[[bin]]
name = "run_day"
path = "src/run_day.rs"

[dependencies]
binary-heap-plus = "0.5.0"
colored = "2.1.0"
dedent = "0.1.1"
num = "0.4.3"
palette = "0.7.6"
regex = "1.11.1"
