[workspace]
resolver = "3"
members = [
    "shared",
    "aoc-2022",
    "aoc-2024",
    "runner",
]

[workspace.dependencies]
# Shared dependencies across all crates
colored = "2.1.0"
itertools = "0.14.0"
regex = "1.11.1"
num = "0.4.3"
